name: SharedHealth
main: pl.dans.plugins.sharedhealth.SharedHealth
version: 1.0
  
commands:
    startGame:
        description: Starts SharedHealth
        usage: /<command> 
        permission: SharedHealth.basic
        permission-message: You don't have <permission>
    stopGame:
        description: Stops SharedHealth
        usage: /<command> 
        permission: SharedHealth.basic
        permission-message: You don't have <permission>
permissions:
    SharedHealth.basic:
        description: Allows use of the commands in the plugin
        default: op
